{% set version="0.6.1" %}
# When updating, also need to update model reference in post-link.sh

package:
  name: deepvariant
  version: {{ version }}

# Things to work on:
# - Uses pre-built binaries, building problematic due to clif dependency
# - Need recent kernel with GLIBC > 2.23 due to pre-built htslib
# - Build patches __main__.py in zip files to generalize python dependency
# - Requires numpy 1.14, want to sync with CONDA_NPY
# - Uses python wrappers that don't expose all underlying options
# - Ships with pre-built model. Longer term will need way to fetch models on demand.

source:
  fn: deepvariant-{{ version }}.tar.gz
  url: https://github.com/google/deepvariant/archive/v0.6.1.tar.gz
  md5: ea80e7bfe91ac4e520220aef93a6f197
  #fn: deepvariant-{{ version }}.zip
  #url: https://github.com/google/deepvariant/releases/download/v{{ version }}/deepvariant.zip
  #md5: e7615109b4d1afe8527605eeaf3f927e

build:
  number: 0
  skip: true  # [osx or not py27]

requirements:
  build:
    - python
    - unzip
    - zip
    - zlib {{CONDA_ZLIB}}*
    - curl
    # Needed for non-binary build
    - numpy 1.14.*
    - tensorflow
    - google-cloud-sdk
    - openssl
    # Need bazel 0.11 due to compile problems
    # https://github.com/tensorflow/tensorflow/issues/18450
    - bazel 0.11.*
  run:
    - openjdk >=8,<9
    - python
    - google-cloud-sdk
    - zlib {{ CONDA_ZLIB }}*
    - boost {{ CONDA_BOOST }}*
    - htslib {{ CONDA_HTSLIB }}*
    - numpy 1.14.*
    - curl
    - tensorflow
    - contextlib2
    - enum34
    - intervaltree
    - mock
    - requests
    - scipy
    - oauth2client
    - six
    - crcmod
    - parallel

test:
  commands:
    # Pre-built binaries need GLIBC 2.16 and 2.23 (htslib) so fail
    - dv_make_examples.py -h
    - dv_call_variants.py -h
    - dv_postprocess_variants.py -h

about:
  home: https://github.com/google/deepvariant
  license: MIT
  summary: DeepVariant is an analysis pipeline that uses a deep neural network to call genetic variants from next-generation DNA sequencing data
